on:
  workflow_call:
    inputs:
      cloudflare-project:
        description: Cloudflare Workers project name
        required: false
        type: string

      hugo-version:
        description: Hugo framework version
        default: 0.164.0
        required: false
        type: string

      cache:
        description: Cache resources
        default: true
        required: false
        type: boolean

    secrets:
      CLOUDFLARE_ACCOUNT_ID:
        description: Cloudflare account ID
        required: false

      CLOUDFLARE_API_TOKEN:
        description: Cloudflare account API token
        required: false

env:
  VERSION: v1.0

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Anthrocon/actions-pages
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.workflow }}
      url: ${{ steps.deploy.outputs.deployment-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

        timeout-minutes: 5
        background: true

      - name: Restore cache
        id: cache
        if: inputs.cache
        uses: actions/cache/restore@v6
        with:
          path: |
            ${{ runner.temp }}/hugo.deb
            ${{ runner.temp }}/hugo_cache
            ./resources

          key: ${{ github.workflow }}-${{ env.VERSION }}-${{ inputs.hugo-version }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.workflow }}-${{ env.VERSION }}-${{ inputs.hugo-version }}-${{ github.ref }}-
            ${{ github.workflow }}-${{ env.VERSION }}-${{ inputs.hugo-version }}-

        timeout-minutes: 5

      - name: Install Hugo
        run: >
          [[ -f ${{ runner.temp }}/hugo.deb ]]
          || wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ inputs.hugo-version }}/hugo_extended_${{ inputs.hugo-version }}_linux-amd64.deb
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

        timeout-minutes: 5

      - name: Wait
        wait-all:

      - name: Build pages
        run: >
          hugo
          --cacheDir ${{ runner.temp }}/hugo_cache
          --enableGitInfo
          --gc
          --minify

      - name: Save cache
        if: inputs.cache
        uses: actions/cache/save@v6
        with:
          path: |
            ${{ runner.temp }}/hugo.deb
            ${{ runner.temp }}/hugo_cache
            ./resources

          key: ${{ steps.cache.outputs.cache-primary-key }}

        timeout-minutes: 5
        background: true

      - name: Deploy Cloudflare Workers
        id: deploy
        if: inputs.cloudflare-project
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./public --project-name=${{ inputs.cloudflare-project }}

        timeout-minutes: 10

      - name: Summarize
        if: steps.deploy.outputs.pages-deployment-id
        run: |
          echo "# :white_check_mark: Deploy to Cloudflare Workers" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Deployment ID | ${{ steps.deploy.outputs.pages-deployment-id }} |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Commit URL | ${{ steps.deploy.outputs.deployment-url }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Branch URL | ${{ steps.deploy.outputs.pages-deployment-alias-url }} |" >> $GITHUB_STEP_SUMMARY

        timeout-minutes: 1

      - name: Wait
        wait-all:

    timeout-minutes: 30
